apiVersion: v1
kind: Service
metadata:
  labels:
    app: ex-rate
  name: ex-rate
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 32221
  selector:
    app: ex-rate